### ISSUE TITLE
Program do not check for target file option -ts 

### ISSUE THREAD

**Issue by secbaymax** [maldevel/intelspy#6]
Dear Maldevel, 

There is logic problem in conditional statement, while using -ts flag. 
It breaks teh loop causing not to verify the file provide with -ts, because of "err set to true" 

can you just comment the statement and realign the loop, so that if singel target is not mentioned, the program checks for the 
fiel path mentioned in -ts arg.

**Line no.1894** 

    if len(raw_targets) == 0:
        error('You must specify at least one target to scan!')
#        err = True

    if len(args.target_file) > 0:

        if not os.path.isfile(args.target_file):
            error('The target file {args.target_file} was not found.')
            sys.exit(1)

**Comment by maldevel** [comment]
fixed in develop branch for next release
